### PR TITLE
Liquidmetal dev

### PR DESCRIPTION
**Pull request by liquid-metal**
Fix for https://github.com/k01ek/netbox-bgp/issues/20

### CODE REVIEW

**Comment by k01ek** [comment]
Did you test it for Netbox 2.10?

**Comment by liquid-metal** [comment]
no not yet
I can do it - is it sufficient to take the latest 2.10 or should I take a specific (or multiple) netbox versions?

**Comment by k01ek** [comment]
any of 2.10.x is acceptable

**Comment by liquid-metal** [comment]
works with 2.10.10
Though I noticed that the UI does not look so nice in this version, the inputs are not grouped:
image
Is this related?

**Comment by k01ek** [comment]
object_edit template has been changed since 2.11
https://github.com/netbox-community/netbox/commit/2a517cde9f929846f7bb806dbe0ee37fb17f0832#diff-bb8b9e5d70eeb6275af78d2207d5a4a94ccac0c5cee25ead5a83fc508480ad8f

**Pull request merged**
