### PR TITLE
support for NetBox 3.4

### PR DESCRIPTION
**Pull request by christianharendt**
I would like to add support for NetBox 3.4.

make tests is running fine and I've also tested to add some sessions in a test instance.

### CODE REVIEW

**Comment by saschapapini** [comment]
+1 for this !

**Comment by p4t0k** [comment]
You will get this error when you try to create a new BGP session:

> insert or update on table "netbox_bgp_bgpsession" violates foreign key constraint "netbox_bgp_bgpsession_local_as_id_65b0582c_fk"
> DETAIL:  Key (local_as_id)=(1) is not present in table "netbox_bgp_asn".

There are two constraints involved:

>     "netbox_bgp_bgpsession_local_as_id_65b0582c_fk" FOREIGN KEY (local_as_id) REFERENCES netbox_bgp_asn(id) DEFERRABLE INITIALLY DEFERRED
>     "netbox_bgp_bgpsession_remote_as_id_8f0efc5b_fk" FOREIGN KEY (remote_as_id) REFERENCES netbox_bgp_asn(id) DEFERRABLE INITIALLY DEFERRED

... and quite a lot of code that needs to be changed so it accesses the ipam_asn table.

**Comment by rothbauer** [comment]
You will get this error when you try to create a new BGP session:

> insert or update on table "netbox_bgp_bgpsession" violates foreign key constraint "netbox_bgp_bgpsession_local_as_id_65b0582c_fk"
> DETAIL: Key (local_as_id)=(1) is not present in table "netbox_bgp_asn".

There are two constraints involved:

> "netbox_bgp_bgpsession_local_as_id_65b0582c_fk" FOREIGN KEY (local_as_id) REFERENCES netbox_bgp_asn(id) DEFERRABLE INITIALLY DEFERRED
> "netbox_bgp_bgpsession_remote_as_id_8f0efc5b_fk" FOREIGN KEY (remote_as_id) REFERENCES netbox_bgp_asn(id) DEFERRABLE INITIALLY DEFERRED

... and quite a lot of code that needs to be changed so it accesses the ipam_asn table.

**Comment by morhold** [comment]
+1 for this!

**Comment by deku-m** [comment]
+1 :)

**Comment by rothbauer** [comment]
When I try to add a new BGP session it returns this error after ASN was moved to :

```
<class 'django.db.utils.IntegrityError'>

insert or update on table "netbox_bgp_bgpsession" violates foreign key constraint "netbox_bgp_bgpsession_local_as_id_65b0582c_fk"
DETAIL:  Key (local_as_id)=(5) is not present in table "netbox_bgp_asn".


Python version: 3.10.6
NetBox version: 3.4.1
```

I guess the DB schema still needs to be migrated to use different constraints...?

**Comment by rothbauer** [comment]
> When I try to add a new BGP session it returns this error after ASN was moved to :
> 
> ```
> <class 'django.db.utils.IntegrityError'>
> 
> insert or update on table "netbox_bgp_bgpsession" violates foreign key constraint "netbox_bgp_bgpsession_local_as_id_65b0582c_fk"
> DETAIL:  Key (local_as_id)=(5) is not present in table "netbox_bgp_asn".
> 
> 
> Python version: 3.10.6
> NetBox version: 3.4.1
> ```
> 
> I guess the DB schema still needs to be migrated to use different constraints...?

Ok, my fault, sorry... I just needed to run a migration under the netbox venv:

```
(venv) postgres@netbox-01:/opt/netbox$ python3 netbox/manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, netbox_bgp, netbox_documents, netbox_evpn_vc, netbox_gateways, netbox_service_contracts, netbox_topology_views, nextbox_ui_plugin, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying netbox_bgp.0026_netbox_bgp... OK
```

I will leave it here just in case anyone will hit this as well.

**Comment by berendt** [comment]
@k01ek Can you please take care of this PR and make a 0.9.0 release? Thanks.

**Pull request merged**
